import type { Metadata } from "next"
import localFont from "next/font/local"
import "./globals.css"
import { Toaster } from "sonner"

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
})
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <main>{children}</main>
        <Toaster
          richColors
          closeButton
          expand={true}
          position="top-right"
          toastOptions={{
            unstyled: true,
            classNames: {
              error:
                "bg-white px-5 py-3 rounded-md shadow border-2 border-red-400 -mt-4 left-0 flex gap-x-2 text-[0.7rem] items-center w-full text-red-500",
              success:
                "bg-white px-5 py-3 rounded-md shadow border-2 border-red-400 -mt-4 left-0 flex gap-x-2 text-[0.7rem] items-center w-full text-red-500",
              warning:
                "bg-white px-5 py-3 rounded-md shadow border-2 border-red-400 -mt-4 left-0 flex gap-x-2 text-[0.7rem] items-center w-full text-red-500",
              info: "bg-white px-5 py-3 rounded-md shadow border-2 border-red-400 -mt-4 left-0 flex gap-x-2 text-[0.7rem] items-center w-full text-red-500",
              loading:
                "bg-white px-5 py-3 rounded-md shadow border-2 border-red-400 -mt-4 left-0 flex gap-x-2 text-[0.7rem] items-center w-full text-red-500",
            },
          }}
        />
      </body>
    </html>
  )
}
